
version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study  # You can change those
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d case_study"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  scraper:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/src
    environment:
      DB_URL: postgresql://user:password@postgres:5432/case_study
    command: python main.py

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_URL: postgresql://user:password@postgres:5432/case_study
    command:  python -m uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
